apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dv175q3bv-python 
  janus-idp.io/tekton: dv175q3bv-python
  backstage.io/kubernetes-id: dv175q3bv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dv175q3bv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml