apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dv175q3bv-python
  janus-idp.io/tekton: dv175q3bv-python
  backstage.io/kubernetes-id: dv175q3bv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dv175q3bv-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
