apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dv175q3bv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dv175q3bv-python 
  name: dv175q3bv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dv175q3bv-python 
